# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QMessageBox
from PyQt5.QtCore import QTimer, QProcess, pyqtSignal, QThread
from PyQt5 import QtCore, QtGui, QtWidgets
import src.tools.tools as mytools

import os, re, sys, json

find_project_file = mytools.find_project_file


class LoginThread(QThread):
    result = pyqtSignal(object)
    error = pyqtSignal(str)

    def __init__(self, email, password):
        super().__init__()
        self.email = email
        self.password = password

    def run(self):
       pass


class Ui_Login(QWidget):

    pip_user_id = pyqtSignal(str)

    def __init__(self):
        super(Ui_Login, self).__init__()
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(571, 289)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(170, 90, 251, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(170, 140, 251, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(250, 190, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(220, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        # 禁止窗体 放大缩小
        Form.setFixedSize(571, 289)
        # 禁用窗体最大化
        Form.setWindowFlag(QtCore.Qt.WindowType.WindowMaximizeButtonHint, False)
        # 禁用窗体最小化
        Form.setWindowFlag(QtCore.Qt.WindowType.WindowMinimizeButtonHint, False)
        # 设置窗口 icon
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(
                find_project_file(
                    os.path.normpath(
                        os.path.join(
                            os.path.join(os.path.expanduser("~"), "ChickenBrothers"),
                            "public/head.ico",
                        )
                    )
                )
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        Form.setWindowIcon(icon)
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "云账号登录"))
        self.label.setText(_translate("Form", "账号："))
        self.label_2.setText(_translate("Form", "密码："))
        self.pushButton.setText(_translate("Form", "登录"))
        self.label_3.setText(_translate("Form", "云账号登录"))
        self.changeBind()

    def changeBind(self):
        self.pushButton.clicked.connect(self.login)
        # 设置输入框默认值
        # self.lineEdit.setText("zhangqiaoqing2001@gmail.com")
        # 设置密码框默认值
        # self.lineEdit_2.setText("Tiancity2164.")

    def login(self):
        try:
            # 修改按钮文字
            self.pushButton.setText("登录中...")
            # 禁用所有输入框和按钮
            self.lineEdit.setEnabled(False)
            self.lineEdit_2.setEnabled(False)
            self.pushButton.setEnabled(False)
            account = self.lineEdit.text()
            password = self.lineEdit_2.text()
            if re.match(r"^[\w\.-]+@[\w\.-]+\.\w+$", account):
                self.thread = LoginThread(account, password)
                self.thread.result.connect(self.on_login_success)
                self.thread.error.connect(self.on_login_error)
                self.thread.start()
            else:
                QMessageBox.warning(self, "错误", "请输入正确的邮箱地址")
        except:
            QMessageBox.warning(self, "错误", "登录失败")

    def on_login_success(self, auth_response):
        print(auth_response)
        print(auth_response.user.id)
        # 登录成功处理
        QMessageBox.information(self, "成功", "登录成功！")
        self.lineEdit.setEnabled(True)
        self.lineEdit_2.setEnabled(True)
        self.pushButton.setEnabled(True)
        self.pushButton.setText("登录")
        self.pip_user_id.emit(auth_response.user.id)
        self.close()

    def on_login_error(self, error_message):
        # 显示错误信息
        QMessageBox.warning(self, "错误", error_message)
        self.lineEdit.setEnabled(True)
        self.lineEdit_2.setEnabled(True)
        self.pushButton.setEnabled(True)
        self.pushButton.setText("登录")
        self.pip_user_id.emit("")

    def closeEvent(self, event):
        self.pip_user_id.emit("")  # 发射信号
        super(Ui_Login, self).closeEvent(event)


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
